# Generated by Django 5.2.10 on 2026-01-10 15:13

from django.db import migrations


def set_new_building_status(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    all_flats = Flat.objects.all()

    for flat in all_flats:
        year = flat.construction_year
        flat.new_building = False if year is None or year < 2015 else True
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(set_new_building_status),
    ]
